name: Greet Everyone Workflow
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./workflows # Uses an action in the root directory
        with:
          who-to-greet: 'Mona the Octocat'
