name: Playwright Tests

on:
  deployment_status:

jobs:
  run-e2es:
    if: github.event_name == 'deployment_status'
    runs-on: ubuntu-latest
    steps:
      - name: Extract serviceDomain
        run: |
          SERVICE_DOMAIN=$(jq -r '.event.deployment.payload.deployment.serviceDeployments[0].serviceDomain' $GITHUB_EVENT_PATH)
          echo "Service Domain: $SERVICE_DOMAIN"
          echo "SERVICE_DOMAIN=$SERVICE_DOMAIN" >> $GITHUB_ENV
        shell: bash
      - name: Debug information
        run: index.js
