name: Extract Deployment URL

on:
  issue_comment:
    types: [created]

jobs:
  extract-url:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'deployment preview URL')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract deployment URL
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          URL_REGEX="https?://[a-zA-Z0-9.-]+/[a-zA-Z0-9-._~:/?#[\\]@!$&'()*+,;=]+"
          if [[ $COMMENT_BODY =~ $URL_REGEX ]]; then
            DEPLOYMENT_URL="${BASH_REMATCH[0]}"
            echo "Deployment URL: $DEPLOYMENT_URL"
            echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV
          else
            echo "No URL found in comment."
          fi
        shell: bash

      # Use the deployment URL in subsequent steps as needed
      - name: Use Deployment URL
        run: |
          echo "Using deployment URL: $DEPLOYMENT_URL"
