name: Playwright Tests

on:
  deployment_status:

jobs:
  run-e2es:
    if: github.event_name == 'deployment_status'
    runs-on: ubuntu-latest
    steps:
      - name: Debug information
        run: |
          echo "Event Name: $GITHUB_EVENT_NAME"
          echo "Event Path: $GITHUB_EVENT_PATH"
          echo "Deployment Status State: ${{ github.event.deployment_status.state }}"
          echo "Environment URL: ${{ github.event.deployment_status.environment_url }}"
        shell: bash
